# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stats_ui_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StatWindow(object):
    def setupUi(self, StatWindow):
        StatWindow.setObjectName("StatWindow")
        StatWindow.resize(853, 575)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(StatWindow.sizePolicy().hasHeightForWidth())
        StatWindow.setSizePolicy(sizePolicy)
        StatWindow.setMinimumSize(QtCore.QSize(0, 517))
        StatWindow.setMaximumSize(QtCore.QSize(942, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icon/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        StatWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(StatWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(260, 160, 241, 111))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 211, 65))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_9 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_9.setObjectName("radioButton_9")
        self.verticalLayout.addWidget(self.radioButton_9)
        self.radioButton = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.checkBox_2 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout.addWidget(self.checkBox_2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(520, 160, 291, 111))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(50, 30, 205, 65))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_3 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 0, 0, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout.addWidget(self.checkBox_4, 1, 0, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout.addWidget(self.checkBox_5, 2, 0, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout.addWidget(self.checkBox_8, 0, 1, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout.addWidget(self.checkBox_6, 1, 1, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout.addWidget(self.checkBox_7, 2, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(40, 160, 191, 141))
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 17, 139, 111))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_11 = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radioButton_11.setObjectName("radioButton_11")
        self.verticalLayout_2.addWidget(self.radioButton_11)
        self.radioButton_10 = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radioButton_10.setObjectName("radioButton_10")
        self.verticalLayout_2.addWidget(self.radioButton_10)
        self.radioButton_12 = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radioButton_12.setObjectName("radioButton_12")
        self.verticalLayout_2.addWidget(self.radioButton_12)
        self.radioButton_14 = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radioButton_14.setObjectName("radioButton_14")
        self.verticalLayout_2.addWidget(self.radioButton_14)
        self.radioButton_13 = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radioButton_13.setObjectName("radioButton_13")
        self.verticalLayout_2.addWidget(self.radioButton_13)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(40, 330, 771, 192))
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(125)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(125)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(40, 20, 321, 131))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 6, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 2, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 5, 0, 2, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget3)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 3, 0, 2, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 2, 1)
        self.layoutWidget4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(450, 20, 361, 74))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget4)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_3.addWidget(self.lineEdit_6, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_3.addWidget(self.lineEdit_5, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 2, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget4)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.gridLayout_3.addWidget(self.comboBox, 2, 1, 1, 1)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(390, 280, 415, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        StatWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StatWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 853, 21))
        self.menubar.setObjectName("menubar")
        StatWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(StatWindow)
        self.statusbar.setObjectName("statusbar")
        StatWindow.setStatusBar(self.statusbar)

        self.retranslateUi(StatWindow)
        QtCore.QMetaObject.connectSlotsByName(StatWindow)

    def retranslateUi(self, StatWindow):
        _translate = QtCore.QCoreApplication.translate
        StatWindow.setWindowTitle(_translate("StatWindow", "Stats"))
        self.groupBox.setTitle(_translate("StatWindow", "Security"))
        self.radioButton_9.setText(_translate("StatWindow", "Unlocked"))
        self.radioButton.setText(_translate("StatWindow", "Pasword Protected"))
        self.checkBox_2.setText(_translate("StatWindow", "SecureStart"))
        self.groupBox_2.setTitle(_translate("StatWindow", "Extraction Type"))
        self.checkBox_3.setText(_translate("StatWindow", "Logical"))
        self.checkBox_4.setText(_translate("StatWindow", "File System"))
        self.checkBox_5.setText(_translate("StatWindow", "Physical"))
        self.checkBox_8.setText(_translate("StatWindow", "Long Term Grey Key"))
        self.checkBox_6.setText(_translate("StatWindow", "Grey Key"))
        self.checkBox_7.setText(_translate("StatWindow", "No Extraction"))
        self.groupBox_3.setTitle(_translate("StatWindow", "Device Type"))
        self.radioButton_11.setText(_translate("StatWindow", "Computer"))
        self.radioButton_10.setText(_translate("StatWindow", "Phone"))
        self.radioButton_12.setText(_translate("StatWindow", "Hard Drive"))
        self.radioButton_14.setText(_translate("StatWindow", "Vehilce"))
        self.radioButton_13.setText(_translate("StatWindow", "Thumbdrive/Media Card"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("StatWindow", "Date"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("StatWindow", "Type"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("StatWindow", "Case Number"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("StatWindow", "Item"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("StatWindow", "Manufacture"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("StatWindow", "Model"))
        self.label_3.setText(_translate("StatWindow", "Case Number:"))
        self.label_2.setText(_translate("StatWindow", "Model:"))
        self.label.setText(_translate("StatWindow", "Manufacture:"))
        self.label_4.setText(_translate("StatWindow", "Item Nuimber:"))
        self.label_5.setText(_translate("StatWindow", "Crime Code:"))
        self.label_6.setText(_translate("StatWindow", "Requesting Unit/Agency:"))
        self.label_7.setText(_translate("StatWindow", "Examiner:"))
        self.pushButton.setText(_translate("StatWindow", "Add DeviceTo Table"))
        self.pushButton_4.setText(_translate("StatWindow", "Remove From Table"))
        self.pushButton_2.setText(_translate("StatWindow", "Commit Devices to DB"))
        self.pushButton_3.setText(_translate("StatWindow", "Close Program"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StatWindow = QtWidgets.QMainWindow()
    ui = Ui_StatWindow()
    ui.setupUi(StatWindow)
    StatWindow.show()
    sys.exit(app.exec_())
